"""Fake normalized lobby so you can run the whole UI with no game open (VALO_MOCK=1)."""

MOCK_LOBBY = {
    "state": "coregame",
    "players": [
        {"puuid": "me", "is_me": True, "team": "ally", "agent": "Jett",
         "account_level": 210, "hidden_level": False, "incognito": False, "tier": 18,
         "form": {"games": 10, "winrate": 0.5, "rr_trend": 20}},
        {"puuid": "a2", "is_me": False, "team": "ally", "agent": "Sage",
         "account_level": 34, "hidden_level": False, "incognito": False, "tier": 12,
         "form": {"games": 10, "winrate": 0.3, "rr_trend": -40}},
        {"puuid": "a3", "is_me": False, "team": "ally", "agent": "Reyna",
         "account_level": 88, "hidden_level": False, "incognito": False, "tier": 15,
         "form": {"games": 10, "winrate": 0.4, "rr_trend": -10}},
        {"puuid": "a4", "is_me": False, "team": "ally", "agent": "Omen",
         "account_level": 305, "hidden_level": False, "incognito": False, "tier": 17,
         "form": {"games": 10, "winrate": 0.6, "rr_trend": 55}},
        {"puuid": "a5", "is_me": False, "team": "ally", "agent": "Sova",
         "account_level": 150, "hidden_level": False, "incognito": False, "tier": 16,
         "form": {"games": 10, "winrate": 0.5, "rr_trend": 5}},
        {"puuid": "e1", "is_me": False, "team": "enemy", "agent": "Raze",
         "account_level": 22, "hidden_level": False, "incognito": False, "tier": 22,
         "form": {"games": 10, "winrate": 0.9, "rr_trend": 180}},
        {"puuid": "e2", "is_me": False, "team": "enemy", "agent": "Cypher",
         "account_level": 240, "hidden_level": False, "incognito": False, "tier": 18,
         "form": {"games": 10, "winrate": 0.6, "rr_trend": 40}},
        {"puuid": "e3", "is_me": False, "team": "enemy", "agent": "Killjoy",
         "account_level": 190, "hidden_level": False, "incognito": False, "tier": 19,
         "form": {"games": 10, "winrate": 0.7, "rr_trend": 70}},
        {"puuid": "e4", "is_me": False, "team": "enemy", "agent": "Astra",
         "account_level": 410, "hidden_level": False, "incognito": False, "tier": 18,
         "form": {"games": 10, "winrate": 0.5, "rr_trend": 0}},
        {"puuid": "e5", "is_me": False, "team": "enemy", "agent": "Phoenix",
         "account_level": 120, "hidden_level": False, "incognito": False, "tier": 17,
         "form": {"games": 10, "winrate": 0.6, "rr_trend": 30}},
    ],
}
